# Create your tests here.
POST http://127.0.0.1:8000/api/user/register/
Content-Type: application/json

{ "email": "prem@mail.com", "username": "prem", "password": "12345","password2": "12345", "userType": "employer"}

###
POST http://127.0.0.1:8000/api/user/login/
Content-Type: application/json

{ "email": " raheem@example.com", "password": "12345"}